version: "3"
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3309:3306"
    volumes:
      - users-db:/var/lib/mysql
volumes:
  users-db: