server:
  port: 8190
  servlet:
    context-path: /whiskers-petshop-carts
integrations:
  product-service:
    url: http://localhost:8189/whiskers-petshop-core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000