server:
  port: 8189
  servlet:
    context-path: /whiskers-petshop-core
spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whiskers_petshop?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
volumes:
  my-db:
integrations:
  cart-service:
    url: http://localhost:8190/whiskers-petshop-carts
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
